on:
  push:
    branches:
    - main
jobs:
  test:
    name: Tesr
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: run tests
      run: |
        dotnet test
