name: API Tests

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest  # Choose an appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '3.1'  # Adjust to the version you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run API Tests
      run: dotnet test --configuration Release
